steps:
  - name: Checkout code
    uses: actions/checkout@v3
    with:
      persist-credentials: true  # laat de GITHUB_TOKEN creds aanhouden
      fetch-depth: 0            # volledige geschiedenis voor push

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: pip install requests python-dotenv

  - name: Write .env from secrets
    run: |
      echo "SHOP_NAME=${{ secrets.SHOP_NAME }}" > .env
      echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env

  - name: Generate variant_sales.json
    run: python fetch_sales.py

  - name: Commit & push JSON
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: "⟳ Update variant_sales.json"
      file_pattern: variant_sales.json